### PR TITLE
Exports the Solid Playground for use in Docs

### PR DESCRIPTION
**Pull request by Jutanium**
If I was a better open-source denizen, this would be a far more detailed write-up explaining everything that @modderme123 did, but because I don't **understand** everything that Milo did and I don't want to bug him to write it up, I'm going to summarize:

- The Solid Playground/repl project exports a `Repl` component that works independently to the Solid Playground site
- Because this relies on web workers and `document`, it doesn't work nicely in Solid Start, which doesn't allow `stubs` (this was a concept Milo taught me)
- To fix this, Milo effectively replaced the imports when the code runs on the server.

### CODE REVIEW

**Review by crutchcorn — APPROVED** [review]
Generally LGTM, some minor thoughts (non blocking):

- @Jutanium raised concern that "solid-start" should have a way to run code on client. While this is true, this is similar to how I'd write this within NextJS
- Future versions of `MyRepl` would be nice to grab files from a file's contents. I'm sure that's the next step.

Overall, let's gooo

**Comment by modderme123** [comment]
What do you mean by grab files from a file's contents? Do you mean allowing passing https://github.com/solidjs/solid-docs-next/blob/playground-test/src/components/repl.tsx#L49-L68 as a parameter?

**Comment by crutchcorn** [comment]
@modderme123 exactly right. I'm not worried about it as a blocker for this PR

**Comment by modderme123** [comment]
My current guess is that the build issue has to do with us running two rollup instances in parallel for two worker imports, and then rollup gets confused that it is called twice and has some outstanding async plugins that are actually for another rollup instance

Some issues that we ran into with rollup and parallelism are described here: https://github.com/vitejs/vite/pull/2689, maybe those would be useful if anyone is willing to help debug this.

**Comment by modderme123** [comment]
Ok, the linked thread says that terser breaks everything without extremely careful work (and I no longer remember what), so someone might try disabling terser in solid-start to see if that works

**Pull request closed without merging**
