### PR TITLE
Update broken links

### PR DESCRIPTION
**Pull request by kulshekhar**

### CODE REVIEW

**Review by michaelessiet — CHANGES_REQUESTED** [review]
Please make use of the paths defined in the NAV_SECTIONS.tsx e.g(/references/concepts/reactivity/tracking) file instead of relative file paths

**Comment by kulshekhar** [comment]
@michaelessiet is there an example or a reference on how this should be done? 

Both `npm run dev` and `npm run start` fail to work locally so I can't test the changes locally and I don't have enough experience with mdx to be able to push changes confidently without testing locally.

Also, I don't see any usage of this in existing mdx files. Is there a strong reason to block this PR on this?

**Comment by kulshekhar** [comment]
nvm. I misunderstood your comment to mean that I should import and use `NAV_SECTIONS`.
I've updated the PR with the absolute paths instead of relative ones

**Comment by michaelessiet** [comment]
> 

Hi, this is a compatibility issue with node version 18 and 19. When trying to run the project make use of node version 16

**Review by michaelessiet — APPROVED** [review]

**Pull request merged**
