### PR TITLE
Submission for issues #61 Grammar, #62 Add Clear directives.  Plus so…

### PR DESCRIPTION
**Pull request by Hopelezz**
…me mods to a few other sections.

*First-time pull request here!*

I'm still working through the other half of the file but wanted to go ahead and send what I've done for release since it clears the issues I've created.

### CODE REVIEW

**Comment by Jutanium** [comment]
Hey, thanks for this! These are great changes.

I want to add something about exclamation points to the writing guide. 

In general, I don't think it's the job of the tutorial to hype things up or have an "exciting" tone.

Nick's original draft had some exclamation pints, but I'm thinking about keeping these to a minimum.

Thoughts?

**Comment by Jutanium** [comment]
Hey @Hopelezz, let me know if these tweaks look good to you, and I'll merge!

**Review by Hopelezz — COMMENTED** [review]
Good catch.

**Review by Hopelezz — COMMENTED** [review]
Oh, That's neat I'll try and make it a point to do this.

**Comment by Hopelezz** [comment]
Hey, everything seems to be good with me. Feel free to merge. I'll take the pointers you've mentioned here and try to apply them going forward. Thanks for the advice.

**Pull request merged**
