### PR TITLE
Style and formatting fixes

### LINKED ISSUE #237: Formatting errors
1. [`Guides/Foundations/Thinking Solid`](https://docs.solidjs.com/guides/foundations/thinking-solid) uses numbers in each subheading. This causes numbers to appear twice in the page summary

CleanShot 2023-03-19 at 13 34 29

2. [`Guides/Tutorials/Getting Started with Solid/Control Flow`](https://docs.solidjs.com/guides/tutorials/getting-started-with-solid/control-flow) `<` and `>` not rendering properly.

CleanShot 2023-03-19 at 13 35 43

### PR DESCRIPTION
**Pull request by Brian-Pob**
Resolves #237 

1. Transform HTML entities into characters in [Control Flow](https://docs.solidjs.com/guides/tutorials/getting-started-with-solid/control-flow)

1. Removed numbers from subheadings in [Thinking Solid](https://docs.solidjs.com/guides/foundations/thinking-solid)
Removed numbers from subheadings

1. Removed bottom padding from body
CleanShot 2023-03-22 at 20 06 45

### CODE REVIEW

**Comment by michaelessiet** [comment]
Hi Brian, there was an earlier PR that handled the section HTML entity issue. I would like to restore the file concerning the correction in your PR is that good by you?

**Comment by Brian-Pob** [comment]
No problem! That's alright with me

**Comment by michaelessiet** [comment]
> No problem! That's alright with me

You'll actually have to restore the file from your end. I thought it would work from here but it isn't

**Comment by Brian-Pob** [comment]
@michaelessiet sorry it took a while. I have removed my changes in my latest commit.

**Pull request closed without merging**
