### PR TITLE
Warning for solid-start

### PR DESCRIPTION
**Pull request by boehs**
image

I don't really like the color but this general thing should probably be done considering half the docs are missing

### CODE REVIEW

**Comment by boehs** [comment]
Frankly maybe this was a mistake, rereading it it's even scaring me!

**Comment by nksaraf** [comment]
Can we use a more yellowish color? the orange doesnt look right..

**Comment by boehs** [comment]
> Can we use a more yellowish color? the orange doesnt look right..

Agreed. How does this look? We might need to turn the text color to black for light colors like this

image

**Comment by nksaraf** [comment]
I think the dark color might be better for the text in the warning box..

**Comment by boehs** [comment]
image

**Comment by boehs** [comment]
Looks great imao, text underline is a tad odd but

**Pull request merged**
